name: build and deploy

on:
  workflow_call:
    inputs:
      DOCKER_REPO:
         required: true
         type: string
      DOCKER_REGISTRY: 
        required: true
        type: string
      DOCKER_USER:
        required: false
        default: "builder"
        type: string
      QEMU_SETUP:
        required: false
        default: "false"
        type: string
      DEPLOY_URL: 
        required: false
        default: "INVALID"        
        type: string
      USE_PULL_REPO:
        required: false
        type: string        
        default: "true"
      USE_YARN: 
        required: false
        type: string        
        default: "true"
      CI: 
        required: false
        type: string        
        default: "true"        
      VAULT_ADDR:
        required: true
        type: string
      VAULT_ROLE:
        required: true
        type: string   
      VAULT_PATH_DOCKER_PASSWORD:
        required: true
        type: string
      VAULT_PATH_AUTH_TOKEN:
        required: false
        type: string

jobs:
  docker_build:
    name: "build docker image and deploy"
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: [self-hosted]
    
    steps:

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.5.0
        with:
          method: jwt
          url: ${{ input.VAULT_ADDR }}
          role: ${{ input.VAULT_ROLE }}
          secrets: |
              ${{ input.VAULT_PATH_DOCKER_PASSWORD }} password | DOCKER_PASSWORD ; 
              ${{ input.VAULT_PATH_AUTH_TOKEN }} token | DOCKER_COMPOSE_DEPLOY_TOKEN ; 
              
      - uses: actions/checkout@v2

      - uses: athenarc/actions-npm-build@master
        id: npm_build
        with:
          USE_YARN: "${{ inputs.USE_YARN }}"
          CI: "${{ inputs.CI }}"

      - uses: athenarc/actions-docker-build-push@master
        id: docker_build
        with:
          DOCKER_REGISTRY: "${{ inputs.DOCKER_REGISTRY }}"
          DOCKER_REPO: "${{ inputs.DOCKER_REPO }}"
          QEMU_SETUP: "${{ inputs.QEMU_SETUP }}"
          DOCKER_USER: "${{ inputs.DOCKER_USER }}"
          DOCKER_PASSWORD: "${{ env.DOCKER_PASSWORD }}"
          CI: "${{ inputs.CI }}"

      - uses: athenarc/actions-docker-compose-deploy@master
        id: docker_deploy
        with:
          AUTH_TOKEN: "${{ env.DOCKER_COMPOSE_DEPLOY_TOKEN }}"
          USE_PULL_REPO: "${{ inputs.USE_PULL_REPO }}"
          DEPLOY_URL: "${{ inputs.DEPLOY_URL }}"
          IMAGES: "${{ steps.docker_build.outputs.images }}"
